-----
title: "Brazil"
author: "Daniel Sun"
date: "2023-03-05"
output: pdf_document
---
```{r}
library(MASS)
library(stargazer)
library(pglm)
library(texreg)
library(lmtest)
brazil <- read.csv("~/brazil.csv")
```

```{r}
#create year dummy variables
brazil$y2010 <- ifelse(brazil$year == 2010, 1, 0)
brazil$y2012 <- ifelse(brazil$year == 2012, 1, 0)
brazil$y2014 <- ifelse(brazil$year == 2014, 1, 0)
brazil$y2016 <- ifelse(brazil$year == 2016, 1, 0)
brazil$y2018 <- ifelse(brazil$year == 2018, 1, 0)
brazil$norte <- ifelse(brazil$estratopri == 1501, 1, 0)

save(brazil, file="brazil.RData")
```

```{r}
brazil$id <- NULL
names(brazil)[names(brazil) == "X"] <- "id"
#create new dataframe omiting NAs in independent variable
brazil2 <- brazil[!is.na(brazil$cct1),]

#recode dependent variable 
brazil2$gl0F <- ifelse(
  brazil2$gl0 == 5, "Never",
  ifelse(
    brazil2$gl0 == 4, "Rarely", 
    ifelse(
      brazil2$gl0 == 3, "Somewhat Likely",
      ifelse(
        brazil2$gl0 == 2, "Likely", 
        ifelse(
          brazil2$gl0 == 1, "Daily", NA
        )))))

brazil2$cp8F <- ifelse(
  brazil2$cp8 == 4, "Unlikely", 
  ifelse(
    brazil2$cp8 == 3, "Somewhat Likely",
    ifelse(
      brazil2$cp8 == 2, "Likely", 
      ifelse(
        brazil2$cp8 == 1, "Very Likely", NA
        ))))

brazil2$cp13F <- ifelse(
 brazil2$cp13 == 4, "Unlikely", 
  ifelse(
    brazil2$cp13 == 3, "Somewhat Likely",
    ifelse(
      brazil2$cp13 == 2, "Likely", 
      ifelse(
        brazil2$cp13 == 1, "Very Likely", NA
        ))))

brazil2$cp7F <- ifelse(
 brazil2$cp7 == 4, "Unlikely", 
  ifelse(
    brazil2$cp7 == 3, "Somewhat Likely",
    ifelse(
      brazil2$cp7 == 2, "Likely", 
      ifelse(
        brazil2$cp7 == 1, "Very Likely", NA
        ))))

brazil2$cp6F <- ifelse(
 brazil2$cp6 == 4, "Unlikely", 
  ifelse(
    brazil2$cp6 == 3, "Somewhat Likely",
    ifelse(
      brazil2$cp6 == 2, "Likely", 
      ifelse(
        brazil2$cp6 == 1, "Very Likely", NA
        ))))

brazil2$cp20F <- ifelse(
 brazil2$cp20 == 4, "Unlikely", 
  ifelse(
    brazil2$cp20 == 3, "Somewhat Likely",
    ifelse(
      brazil2$cp20 == 2, "Likely", 
      ifelse(
        brazil2$cp20 == 1, "Very Likely", NA
        ))))

brazil2$b21aF <- ifelse(
  brazil2$b21a == 1, "Not at all",
  ifelse(
    brazil2$b21a == 2, "2",
    ifelse(
      brazil2$b21a == 3, "3",
      ifelse(
        brazil2$b21a == 4, "4",
        ifelse(
          brazil2$b21a == 5, "5",
          ifelse(
            brazil2$b21a == 6, "6",
            ifelse(
              brazil2$b21a == 7, "A Lot", NA
            )
          )
        )
      )
    )
  )
)

brazil2$b32F <- ifelse(
  brazil2$b32 == 1, "Not at all",
  ifelse(
    brazil2$b32 == 2, "2",
    ifelse(
      brazil2$b32 == 3, "3",
      ifelse(
        brazil2$b32 == 4, "4",
        ifelse(
          brazil2$b32 == 5, "5",
          ifelse(
            brazil2$b32 == 6, "6",
            ifelse(
              brazil2$b32 == 7, "A Lot", NA
            )
          )
        )
      )
    )
  )
)

brazil2$b13F <- ifelse(
  brazil2$b13 == 1, "Not at all",
  ifelse(
    brazil2$b13 == 2, "2",
    ifelse(
      brazil2$b13 == 3, "3",
      ifelse(
        brazil2$b13 == 4, "4",
        ifelse(
          brazil2$b13 == 5, "5",
          ifelse(
            brazil2$b13 == 6, "6",
            ifelse(
              brazil2$b13 == 7, "A Lot", NA
            )
          )
        )
      )
    )
  )
)

brazil2$b21F <- ifelse(
 brazil2$b21 == 1, "Not at all",
  ifelse(
    brazil2$b21 == 2, "2",
    ifelse(
      brazil2$b21 == 3, "3",
      ifelse(
        brazil2$b21 == 4, "4",
        ifelse(
          brazil2$b21 == 5, "5",
          ifelse(
            brazil2$b21 == 6, "6",
            ifelse(
              brazil2$b21 == 7, "A Lot", NA
            )
          )
        )
      )
    )
  )
)

brazil2$pol1F <- ifelse(
 brazil2$pol1 == 4, "Never", 
  ifelse(
    brazil2$pol1 == 3, "A Little",
    ifelse(
      brazil2$pol1 == 2, "Some", 
      ifelse(
        brazil2$pol1 == 1, "A Lot", NA
        ))))

#use this to make IVs a factor variable with specific levels. 
brazil2$gl0F <- factor(brazil2$gl0F, levels = c("Never",
                                                "Rarely",
                                                "Somewhat Likely",
                                                "Likely",
                                                "Daily"))

brazil2$pol1F <- factor(brazil2$pol1F, levels=c("Never", 
                                              "A Little",
                                              "Some", 
                                              "A Lot"))

brazil2$cp8F <- factor(brazil2$cp8F, levels=c("Unlikely", 
                                              "Somewhat Likely",
                                              "Likely", 
                                              "Very Likely"))

brazil2$cp13F <- factor(brazil2$cp13F, levels=c("Unlikely", 
                                              "Somewhat Likely",
                                              "Likely", 
                                              "Very Likely"))

brazil2$cp7F <- factor(brazil2$cp7F, levels=c("Unlikely", 
                                              "Somewhat Likely",
                                              "Likely", 
                                              "Very Likely"))

brazil2$cp6F <- factor(brazil2$cp6F, levels=c("Unlikely", 
                                              "Somewhat Likely",
                                              "Likely", 
                                              "Very Likely"))

brazil2$cp20F <- factor(brazil2$cp20F, levels=c("Unlikely", 
                                              "Somewhat Likely",
                                              "Likely", 
                                              "Very Likely"))

brazil2$b21aF <- factor(brazil2$b21aF, levels=c("Not at all", 
                                                "2",
                                                "3",
                                                "4",
                                                "5",
                                                "6",
                                                "A Lot"
))

brazil2$b32F <- factor(brazil2$b32F, levels=c("Not at all", 
                                                "2",
                                                "3",
                                                "4",
                                                "5",
                                                "6",
                                                "A Lot"
))

brazil2$b13F <- factor(brazil2$b13F, levels=c("Not at all", 
                                                "2",
                                                "3",
                                                "4",
                                                "5",
                                                "6",
                                                "A Lot"
))

brazil2$b21F <- factor(brazil2$b21F, levels=c("Not at all", 
                                                "2",
                                                "3",
                                                "4",
                                                "5",
                                                "6",
                                                "A Lot"
))
```

```{r}
#Nonfixed
cp8bnf <- polr(cp8F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur ,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp8bcoef <- exp(coef(cp8bnf))

cp13bnf <- polr(cp13F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp13bcoef <- exp(coef(cp13bnf))

cp7bnf <- polr(cp7F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp7bcoef <- exp(coef(cp7bnf))

cp6bnf <- polr(cp6F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp6bcoef <- exp(coef(cp6bnf))

cp20bnf <- polr(cp20F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp20bcoef <- exp(coef(cp20bnf))

b32bnf <- polr(b32F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b32bcoef <- exp(coef(b32bnf))

b13bnf <- polr(b13F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b13bcoef <- exp(coef(b13bnf))

b21bnf <- polr(b21F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21bcoef <- exp(coef(b21bnf))

b21abnf <- polr(b21aF ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21abcoef <- exp(coef(b21abnf))

vb10bnf <- glm(vb10 ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb10bcoef = exp(coef(vb10bnf))

#regression table for nonfixed civic engagement
stargazer(cp8bnf, cp13bnf, cp7bnf, cp6bnf, cp20bnf, b32bnf, b13bnf, b21bnf, b21abnf, vb10bnf,
          coef = list(cp8bcoef, cp13bcoef, cp7bcoef, cp6bcoef, cp20bcoef, b32bcoef, b13bcoef, b21bcoef, b21abcoef, vb10bcoef),
          column.labels = c("Community", "Parent", "Party Mtg", "RelOrgs", "WomenGrp", "ExecTrust", "LGovTrust", "PolTrust", "LegTrust"),
          p.auto = F,
          align = T,
          type = "text"
)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
#Fixed
cp8bfix <- polr(cp8F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,  #these are the yearly fixed effects
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp8bfixcoef <- exp(coef(cp8bfix))

cp13bfix <- polr(cp13F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur+ factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp13bfixcoef <- exp(coef(cp13bfix))

cp7bfix <- polr(cp7F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp7bfixcoef <- exp(coef(cp7bfix))

cp6bfix <- polr(cp6F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur+ factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp6bfixcoef <- exp(coef(cp6bfix))

cp20bfix <- polr(cp20F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp20bfixcoef <- exp(coef(cp20bfix))

b32bfix <- polr(b32F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b32bfixcoef <- exp(coef(b32bfix))

b13bfix <- polr(b13F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b13bfixcoef <- exp(coef(b13bfix))

b21bfix <- polr(b21F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21bfixcoef <- exp(coef(b21bfix))

b21abfix <- polr(b21aF ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21abfixcoef <- exp(coef(b21abfix))

vb10bfix <- glm(vb10 ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb10bfixcoef = exp(coef(vb10bfix))

#regression table for fixed effects - civic engagement
stargazer(cp8bfix, cp13bfix, cp7bfix, cp6bfix, cp20bfix,
          coef = list(cp8bfixcoef, cp13bfixcoef, cp7bfixcoef, cp6bfixcoef, cp20bfixcoef),
          column.labels = c("Community", "PartyMtg", "Parent", "RelOrgs", "WomenGrp"),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Civic Engagement"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Party Trust", "Local Government Trust", "Leg Trust", "Exec Trust", "Urban/Rural", "2012", "2014", "2016", "2018"),
          title = "Table 4: Brazil Logistic Regression, Civic Engagement",
          add.lines=list(c("AIC", round(AIC(cp8bfix), 1), round(AIC(cp13bfix), 1), round(AIC(cp7bfix), 1), round(AIC(cp6bfix), 1), round(AIC(cp20bfix), 1)), c("BIC", round(BIC(cp8bfix), 1), round(BIC(cp13bfix), 1), round(BIC(cp7bfix), 1), round(BIC(cp6bfix), 1), round(BIC(cp20bfix), 1)))
)

stargazer(b32bfix, b13bfix, b21bfix, b21abfix,
          column.labels = c("LGovTrust", "LegTrust", "PolTrust", "ExecTrust"),
          coef = list(b32bfixcoef, b13bfixcoef, b21bfixcoef, b21abfixcoef, vb10bfixcoef),
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Urban/Rural", "2012", "2014", "2016", "2018"),
          title = "Table 6: Brazil Regression, Trust",
          dep.var.caption = c("Trust"),
          add.lines = list(c("AIC", round(AIC(b32bfix), 1), round(AIC(b13bfix), 1), round(AIC(b21bfix), 1), round(AIC(b21abfix), 1)), c("BIC", round(BIC(b32bfix), 1), round(BIC(b13bfix), 1), round(BIC(b21bfix), 1),round(BIC(b21abfix), 1)))
)
```

```{r}
#Nonfixed Political Participation
prot3bnf <- glm(prot3 ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
prot3bcoef = exp(coef(prot3bnf))

vb2bnf <- glm(vb2 ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb2bcoef = exp(coef(vb2bnf))

pol1bnf <- polr(pol1F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a,
             data = brazil2,
             method = "logistic", Hess=TRUE)
pol1bcoef = exp(coef(pol1bnf))

gl0bnf <- polr(gl0F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a,
             data = brazil2,
             method = "logistic", Hess=TRUE)
gl0bcoef = exp(coef(gl0bnf))


#Regression for Political Participation - nonfixed
stargazer(prot3bnf, vb2bnf, pol1bnf, gl0bnf,
          coef = list(prot3bcoef, vb2bcoef, pol1bcoef, gl0bcoef),
          p.auto = F,
          align = T,
          type = "text",
          
)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
#Fixed Political Participation
prot3bfix <- glm(prot3 ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
prot3bfixcoef = exp(coef(prot3bfix))

vb2bfix <- glm(vb2 ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb2bfixcoef = exp(coef(vb2bfix))

pol1bfix <- polr(pol1F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
pol1bfixcoef = exp(coef(pol1bfix))

gl0bfix <- polr(gl0F ~ cct1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
gl0bfixcoef = exp(coef(gl0bfix))

stargazer(prot3bfix, vb2bfix, pol1bfix, gl0bfix, vb10bfix,
          coef = list(prot3bfixcoef, vb2bfixcoef, pol1bfixcoef, gl0bfixcoef, vb10bfixcoef),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Political Participation"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Party Trust", "Local Government Trust", "Leg Trust", "Exec Trust", "Urban/Rural", "2012", "2014", "2016", "2018"),
          title = "Table 5: Brazil Regression, Political Participation",
          column.labels = c("Protest", "VotedLastYear", "PolInterest", "WatchNews", "PolID"),
          add.lines=list(c("AIC", round(AIC(prot3bfix), 1), round(AIC(vb2bfix), 1), round(AIC(pol1bfix), 1), round(AIC(gl0bfix), 1), round(AIC(vb10bfix), 1)), c("BIC", round(BIC(prot3bfix), 1), round(BIC(vb2bfix), 1), round(BIC(pol1bfix), 1), round(BIC(gl0bfix), 1), round(BIC(vb10bfix), 1)))
)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
##Interactions - Gender
cp8bfixint <- polr(cp8F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp8bfixintcoef <- exp(coef(cp8bfixint))

cp13bfixint <- polr(cp13F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp13bfixintcoef <- exp(coef(cp13bfixint))

cp7bfixint <- polr(cp7F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp7bfixintcoef <- exp(coef(cp7bfixint))

cp6bfixint <- polr(cp6F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp6bfixintcoef <- exp(coef(cp6bfixint))

cp20bfixint <- polr(cp20F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp20bfixintcoef <- exp(coef(cp20bfixint))

b32bfixint <- polr(b32F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b32bfixintcoef <- exp(coef(b32bfixint))

b13bfixint <- polr(b13F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b13bfixintcoef <- exp(coef(b13bfixint))

b21bfixint <- polr(b21F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21bfixintcoef <- exp(coef(b21bfixint))

b21abfixint <- polr(b21aF ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21abfixintcoef <- exp(coef(b21abfixint))

vb10bfixint <- glm(vb10 ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb10bfixintcoef = exp(coef(vb10bfixint))

stargazer(cp8bfixint, cp13bfixint, cp7bfixint, cp6bfixint, cp20bfixint,
          coef = list(cp8bfixintcoef, cp13bfixintcoef, cp7bfixintcoef, cp6bfixintcoef, cp20bfixintcoef),
          column.labels = c("Community", "PartyMtg", "Parent", "RelOrgs", "WomenGrp"),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Civic Engagement"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Party Trust", "Local Government Trust", "Leg Trust", "Exec Trust", "Urban/Rural", "2012", "2014", "2016", "2018", "norte", "CCT x Gender"),
          title = "Table 10: Brazil Regression with Gender Interaction, Civic Engagement",
          
)

stargazer(b32bfixint, b13bfixint, b21bfixint, b21abfixint,
          coef = list(b32bfixintcoef, b13bfixintcoef, b21bfixintcoef, b21abfixintcoef),
          column.labels = c("LGovTrust", "LegTrust", "PolTrust", "ExecTrust"),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Civic Engagement"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Urban/Rural", "2012", "2014", "2016", "2018", "norte", "CCT x Gender"),
          title = "Table 12: Brazil Regression with Gender Interaction, Trust"
)

prot3bfixint <- glm(prot3 ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
prot3bfixintcoef = exp(coef(prot3bfixint))

vb2bfixint <- glm(vb2 ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb2bfixintcoef = exp(coef(vb2bfixint))

pol1bfixint <- polr(pol1F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
pol1bfixintcoef = exp(coef(pol1bfixint))

gl0bfixint <- polr(gl0F ~ cct1 + cct1*q1 + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte,
               data = brazil2,
               method = "logistic", Hess = T)
gl0bfixintcoef = exp(coef(gl0bfixint))

stargazer(prot3bfixint, vb2bfixint, pol1bfixint, gl0bfixint, vb10bfixint,
          coef = list(prot3bfixintcoef, vb2bfixintcoef, pol1bfixintcoef, gl0bfixintcoef, vb10bfixintcoef),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Political Participation"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Party Trust", "Local Government Trust", "Leg Trust", "Exec Trust", "Urban/Rural", "2012", "2014", "2016", "2018", "norte", "CCT x Gender"),
          title = "Table 11: Brazil Regression with Gender Interaction, Political Participation",
          column.labels = c("Protest", "VotedLastYear", "PolInterest", "WatchNews", "PolID")
)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
##Interactions - Education
cp8bfixinted <- polr(cp8F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp8bfixintedcoef <- exp(coef(cp8bfixinted))

cp13bfixinted <- polr(cp13F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp13bfixintedcoef <- exp(coef(cp13bfixinted))

cp7bfixinted <- polr(cp7F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp7bfixintedcoef <- exp(coef(cp7bfixinted))

cp6bfixinted <- polr(cp6F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp6bfixintedcoef <- exp(coef(cp6bfixinted))

cp20bfixinted <- polr(cp20F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
cp20bfixintedcoef <- exp(coef(cp20bfixinted))

b32bfixinted <- polr(b32F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b32bfixintedcoef <- exp(coef(b32bfixinted))

b13bfixinted <- polr(b13F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b13bfixintedcoef <- exp(coef(b13bfixinted))

b21bfixinted <- polr(b21F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21bfixintedcoef <- exp(coef(b21bfixinted))

b21abfixinted <- polr(b21aF ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
b21abfixintedcoef <- exp(coef(b21abfixinted))

vb10bfixinted <- glm(vb10 ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + b21 + b32 + b13 + b21a + ur + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb10bfixintedcoef = exp(coef(vb10bfixinted))

stargazer(cp8bfixinted, cp13bfixinted, cp7bfixinted, cp6bfixinted, cp20bfixinted,
          coef = list(cp8bfixintedcoef, cp13bfixintedcoef, cp7bfixintedcoef, cp6bfixintedcoef, cp20bfixintedcoef),
          column.labels = c("Community", "Parent", "PartyMtg", "RelOrgs", "WomenGrp"),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Civic Engagement"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Party Trust", "Local Government Trust", "Leg Trust", "Exec Trust", "Urban/Rural", "2012", "2014", "2016", "2018", "norte", "CCT x Education"),
          title = "Table 10: Brazil Regression with Education Interaction, Civic Engagement"
)

stargazer(b32bfixinted, b13bfixinted, b21bfixinted, b21abfixinted,
          coef = list(b32bfixintedcoef, b13bfixintedcoef, b21bfixintedcoef, b21abfixintedcoef),
          column.labels = c("LGovTrust", "LegTrust", "PolTrust", "ExecTrust"),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Civic Engagement"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Urban/Rural", "2012", "2014", "2016", "2018", "norte", "CCT x Education"),
          title = "Table 12: Brazil Regression with Education Interaction, Trust"
)

prot3bfixinted <- glm(prot3 ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
prot3bfixintedcoef = exp(coef(prot3bfixinted))

vb2bfixinted <- glm(vb2 ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte, 
               data = brazil2, 
               family = binomial(link = 'logit')
)
vb2bfixintedcoef = exp(coef(vb2bfixinted))

pol1bfixinted<- polr(pol1F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte,
             data = brazil2,
             method = "logistic", Hess=TRUE)
pol1bfixintedcoef = exp(coef(pol1bfixinted))

gl0bfixinted <- polr(gl0F ~ cct1 + cct1*ed + q1 + q2 + q10 + q5b + q12a + ed + ur + b21 + b32 + b13 + b21a + factor(year) + norte,
               data = brazil2,
               method = "logistic", Hess = T)
gl0bfixintedcoef = exp(coef(gl0bfixinted))

stargazer(prot3bfixinted, vb2bfixinted, pol1bfixinted, gl0bfixinted, vb10bfixinted,
          coef = list(prot3bfixintedcoef, vb2bfixintedcoef, pol1bfixintedcoef, gl0bfixintedcoef, vb10bfixintedcoef),
          p.auto = F,
          align = T,
          type = "text",
          model.names = F,
          model.numbers = F,
          dep.var.labels.include = F,
          dep.var.caption = c("Political Participation"),
          covariate.labels = c("CCT", "Gender", "Age", "Income", "Religion", "Number of Children", "Education", "Party Trust", "Local Government Trust", "Leg Trust", "Exec Trust", "Urban/Rural", "2012", "2014", "2016", "2018", "norte", "CCT x Education"),
          title = "Table 11: Brazil Regression with Education Interaction, Political Participation",
          column.labels = c("Protest", "VotedLastYear", "PolInterest", "WatchNews", "PolID")
)
```